var resources = [{
    "title": "A Treatise on the Theory and Practice of Landscape Gardening",
    "data": {
        "key": "EI2VS2WB",
        "version": 413,
        "itemType": "book",
        "title": "A treatise on the theory and practice of landscape gardening, adapted to North America ...",
        "creators": [{
            "creatorType": "author",
            "firstName": "A. J.",
            "lastName": "Downing"
        }, {
            "creatorType": "author",
            "firstName": "Henry Winthrop",
            "lastName": "Sargent"
        }],
        "abstractNote": "",
        "series": "",
        "seriesNumber": "",
        "volume": "",
        "numberOfVolumes": "",
        "edition": "",
        "place": "New York",
        "publisher": "A. O. Moore & Co.",
        "date": "1859",
        "numPages": "xvi, 576 p.",
        "language": "",
        "ISBN": "",
        "shortTitle": "",
        "url": "https://catalog.hathitrust.org/Record/011602086",
        "accessDate": "2018-03-23T23:16:54Z",
        "archive": "done",
        "archiveLocation": "",
        "libraryCatalog": "Hathi Trust",
        "callNumber": "",
        "rights": "",
        "extra": "LD: 9",
        "tags": [{
            "tag": "Landscape gardening",
            "type": 1
        }],
        "collections": ["LMWECFU5"],
        "relations": {},
        "dateAdded": "2018-03-23T23:16:54Z",
        "dateModified": "2018-03-24T13:21:11Z"
    }
}, {
    "title": "Accents as Well as Broad Effects",
    "data": {
        "key": "IN2CR8MU",
        "version": 3157,
        "itemType": "book",
        "title": "Accents as Well as Broad Effects: Writings on Architecture, Landscape, and the Environment, 1876-1925",
        "creators": [{
            "creatorType": "author",
            "firstName": "Mrs Schuyler Van",
            "lastName": "Rensselaer"
        }, {
            "creatorType": "author",
            "firstName": "Mariana Griswold Van",
            "lastName": "Rensselaer"
        }],
        "abstractNote": "Mariana Griswold Van Rensselaer (1851-1934) is highly regarded among architectural historians for her 1888 biography of the nineteenth-century architect Henry Hobson Richardson. Less well known are her writings on architecture, decorative art, gardening, and landscape design, works that provide a rare view of cities and rural environments in turn-of-the-century America. Now David Gebhard brings Van Rensselaer's significant writings together in one volume, including a chapter from the 1925 edition of Art Out-of-Doors: Hints on Good Taste in Gardening.An established critic in environmental and literary circles, Van Rensselaer wrote for the general public in such journals as the Century Magazine and for a specialized audience of landscape architects in Garden and Forest. She was a long-time contributor to The American Architect and Building News, the first architectural journal in the United States. She is an engaging and accessible writer, and her articles on Frederick Law Olmsted and the Boston Public Library won great praise. Although the only woman in a field that was male-dominated at the time, Van Rensselaer was, curiously enough, opposed to women's suffrage.David Gebhard provides an excellent introduction to this unusual woman and to her place in American architectural criticism. Van Rensselaer's writings are still of interest today, not only for her broad environmental approach, but also for her ability to relate abstract concepts to examples of harmonious design. Mariana Griswold Van Rensselaer (1851-1934) is highly regarded among architectural historians for her 1888 biography of the nineteenth-century architect Henry Hobson Richardson. Less well known are her writings on architecture, decorative art, gardening, and landscape design, works that provide a rare view of cities and rural environments in turn-of-the-century America. Now David Gebhard brings Van Rensselaer's significant writings together in one volume, including a chapter from the 1925 edition of Art Out-of-Doors: Hints on Good Taste in Gardening.An established critic in environmental and literary circles, Van Rensselaer wrote for the general public in such journals as the Century Magazine and for a specialized audience of landscape architects in Garden and Forest. She was a long-time contributor to The American Architect and Building News, the first architectural journal in the United States. She is an engaging and accessible writer, and her articles on Frederick Law Olmsted and the Boston Public Library won great praise. Although the only woman in a field that was male-dominated at the time, Van Rensselaer was, curiously enough, opposed to women's suffrage.David Gebhard provides an excellent introduction to this unusual woman and to her place in American architectural criticism. Van Rensselaer's writings are still of interest today, not only for her broad environmental approach, but also for her ability to relate abstract concepts to examples of harmonious design.",
        "series": "",
        "seriesNumber": "",
        "volume": "",
        "numberOfVolumes": "",
        "edition": "",
        "place": "",
        "publisher": "University of California Press",
        "date": "1996",
        "numPages": "388",
        "language": "en",
        "ISBN": "978-0-520-20126-2",
        "shortTitle": "Accents as Well as Broad Effects",
        "url": "",
        "accessDate": "",
        "archive": "",
        "archiveLocation": "",
        "libraryCatalog": "Google Books",
        "callNumber": "",
        "rights": "",
        "extra": "Google-Books-ID: 5W2P2T9YDkAC",
        "tags": [{
            "tag": "Architecture / History / General",
            "type": 1
        }, {
            "tag": "History / Americas (North, Central, South, West Indies)",
            "type": 1
        }],
        "collections": ["8ZQTCFH5"],
        "relations": {},
        "dateAdded": "2018-09-14T20:56:37Z",
        "dateModified": "2018-09-14T20:56:37Z"
    }
}, {
    "title": "An encyclopædia of agriculture",
    "data": {
        "key": "WYLSCJFT",
        "version": 507,
        "itemType": "book",
        "title": "An encyclopædia of agriculture: comprising the theory and practice of the valuation, transfer, laying out, improvement, and management of landed property; and the cultivation and economy of the animal and vegetable productions of agriculture, including all the latest improvements; a general history of agriculture in all countries; and a statistical view of its present state, with suggestions for its future progress in the British Isles.",
        "creators": [{
            "creatorType": "author",
            "firstName": "J. C.",
            "lastName": "Loudon"
        }],
        "abstractNote": "",
        "series": "",
        "seriesNumber": "",
        "volume": "",
        "numberOfVolumes": "",
        "edition": "2d ed.",
        "place": "London,",
        "publisher": "Printed for Longman, Rees, Orme, Brown, and Green,",
        "date": "1831",
        "numPages": "1332",
        "language": "",
        "ISBN": "",
        "shortTitle": "An encyclopædia of agriculture",
        "url": "https://www.biodiversitylibrary.org/bibliography/28736",
        "accessDate": "",
        "archive": "done",
        "archiveLocation": "",
        "libraryCatalog": "BHL",
        "callNumber": "",
        "rights": "",
        "extra": "LD: 9+",
        "tags": [],
        "collections": ["KXUA5LUF"],
        "relations": {},
        "dateAdded": "2018-03-26T14:31:40Z",
        "dateModified": "2018-03-26T14:36:39Z"
    }
}, {
    "title": "An encyclopædia of plants",
    "data": {
        "key": "QBUHJVPC",
        "version": 507,
        "itemType": "book",
        "title": "An encyclopædia of plants; comprising the description, specific character, culture, history, application in the arts, and every other desirable particular respecting all the plants indigenous, cultivated in, or introduced to Britain, combining all the advantages of a Linnean and Jussieuean species plantarum, an historia plantarum, a grammar of botany, and a dictionary of botany and vegetable culture. The whole in English; with the synonymes of the commoner plants in the different European and other languages ...",
        "creators": [{
            "creatorType": "author",
            "firstName": "J. C.",
            "lastName": "Loudon"
        }],
        "abstractNote": "",
        "series": "",
        "seriesNumber": "",
        "volume": "",
        "numberOfVolumes": "",
        "edition": "",
        "place": "London,",
        "publisher": "Printed for Longman, Rees, Orme, Brown and Green,",
        "date": "1829",
        "numPages": "1192",
        "language": "",
        "ISBN": "",
        "shortTitle": "",
        "url": "https://www.biodiversitylibrary.org/bibliography/100032",
        "accessDate": "",
        "archive": "done",
        "archiveLocation": "",
        "libraryCatalog": "BHL",
        "callNumber": "",
        "rights": "",
        "extra": "LD: 9+",
        "tags": [],
        "collections": ["KXUA5LUF"],
        "relations": {},
        "dateAdded": "2018-03-26T14:32:26Z",
        "dateModified": "2018-03-26T14:35:40Z"
    }
}, {
    "title": "Apostle of Taste: Andrew Jackson Downing",
    "data": {
        "key": "QR23SMLQ",
        "version": 3154,
        "itemType": "book",
        "title": "Apostle of taste : Andrew Jackson Downing, 1815-1852 /",
        "creators": [{
            "creatorType": "author",
            "firstName": "David",
            "lastName": "Schuyler"
        }],
        "abstractNote": "",
        "series": "",
        "seriesNumber": "",
        "volume": "",
        "numberOfVolumes": "",
        "edition": "",
        "place": "Baltimore :",
        "publisher": "Johns Hopkins University Press,",
        "date": "1996.",
        "numPages": "",
        "language": "",
        "ISBN": "978-0-8018-5229-9",
        "shortTitle": "Apostle of taste",
        "url": "",
        "accessDate": "",
        "archive": "",
        "archiveLocation": "",
        "libraryCatalog": "",
        "callNumber": "",
        "rights": "",
        "extra": "",
        "tags": [],
        "collections": ["AYFZDCDI"],
        "relations": {},
        "dateAdded": "2018-09-14T20:46:33Z",
        "dateModified": "2018-09-14T20:46:33Z"
    }
}, {
    "title": "Arboretum et Fruticetum Britannicum",
    "data": {
        "key": "EXCAXZH4",
        "version": 507,
        "itemType": "book",
        "title": "Arboretum et fruticetum britannicum, or : The trees and shrubs of Britain, native and foreign, hardy and half-hardy, pictorially and botanically delineated, and scientifically and popularly described ... /",
        "creators": [{
            "creatorType": "author",
            "firstName": "J. C.",
            "lastName": "Loudon"
        }],
        "abstractNote": "",
        "series": "",
        "seriesNumber": "",
        "volume": "",
        "numberOfVolumes": "",
        "edition": "2nd ed.",
        "place": "London :",
        "publisher": "J.C. Loudon,",
        "date": "1844",
        "numPages": "224",
        "language": "",
        "ISBN": "",
        "shortTitle": "Arboretum et fruticetum britannicum, or",
        "url": "https://www.biodiversitylibrary.org/bibliography/59079",
        "accessDate": "",
        "archive": "done",
        "archiveLocation": "",
        "libraryCatalog": "BHL",
        "callNumber": "",
        "rights": "",
        "extra": "LD: 9+",
        "tags": [],
        "collections": ["KXUA5LUF"],
        "relations": {},
        "dateAdded": "2018-03-26T14:31:16Z",
        "dateModified": "2018-03-26T14:37:15Z"
    }
}, {
    "title": "The Botanical magazine, or, Flower-garden displayed",
    "data": {
        "key": "JXAGYPR8",
        "version": 3158,
        "itemType": "book",
        "title": "The Botanical magazine, or, Flower-garden displayed ... /",
        "creators": [{
            "creatorType": "author",
            "firstName": "William",
            "lastName": "Curtis"
        }, {
            "creatorType": "author",
            "firstName": "Kew",
            "lastName": "Royal Botanic Gardens"
        }],
        "abstractNote": "",
        "series": "",
        "seriesNumber": "",
        "volume": "v.5-6=no.145-216 (1792-1793)",
        "numberOfVolumes": "",
        "edition": "",
        "place": "[S.l. :",
        "publisher": "s.n.],",
        "date": "1792-1793",
        "numPages": "153",
        "language": "",
        "ISBN": "",
        "shortTitle": "",
        "url": "https://www.biodiversitylibrary.org/item/7355",
        "accessDate": "",
        "archive": "",
        "archiveLocation": "",
        "libraryCatalog": "",
        "callNumber": "",
        "rights": "",
        "extra": "",
        "tags": [],
        "collections": ["KXUA5LUF"],
        "relations": {},
        "dateAdded": "2018-09-14T20:57:28Z",
        "dateModified": "2018-09-14T20:57:28Z"
    }
}, {
    "title": "Democracy in America",
    "data": {
        "key": "7JMXQLX8",
        "version": 3161,
        "itemType": "book",
        "title": "Democracy in America",
        "creators": [{
            "creatorType": "author",
            "firstName": "Alexis de",
            "lastName": "Tocqueville"
        }],
        "abstractNote": "",
        "series": "CIHM/ICMH Microfiche series = CIHM/ICMH collection de microfiches ;no. 18597",
        "seriesNumber": "",
        "volume": "",
        "numberOfVolumes": "",
        "edition": "",
        "place": "New York",
        "publisher": "G. Dearborn",
        "date": "1838",
        "numPages": "",
        "language": "",
        "ISBN": "978-0-665-18597-7",
        "shortTitle": "",
        "url": "https://catalog.hathitrust.org/Record/100258681",
        "accessDate": "2018-09-14T20:58:16Z",
        "archive": "",
        "archiveLocation": "",
        "libraryCatalog": "Hathi Trust",
        "callNumber": "",
        "rights": "",
        "extra": "",
        "tags": [{
            "tag": "Conditions sociales",
            "type": 1
        }, {
            "tag": "Democracy.",
            "type": 1
        }, {
            "tag": "Démocratie.",
            "type": 1
        }, {
            "tag": "Jusqu'à 1865",
            "type": 1
        }, {
            "tag": "Politics and government.",
            "type": 1
        }, {
            "tag": "Politique et gouvernement.",
            "type": 1
        }, {
            "tag": "Social conditions",
            "type": 1
        }, {
            "tag": "To 1865",
            "type": 1
        }, {
            "tag": "United States",
            "type": 1
        }, {
            "tag": "États-Unis",
            "type": 1
        }],
        "collections": ["LMWECFU5"],
        "relations": {},
        "dateAdded": "2018-09-14T20:58:16Z",
        "dateModified": "2018-09-14T20:58:16Z"
    }
}, {
    "title": "Designs for Laying Out Farms and farm-buildings in the Scotch style",
    "data": {
        "key": "LU9L2LX3",
        "version": 3164,
        "itemType": "book",
        "title": "Designs for laying out Farms and farm-buildings in the Scotch style; adapted to England: including an account of ... Tew Lodge Farm, Oxfordshire, with an opinion on the subject of breaking up grass lands. Illustrated by forty plates. L.P.",
        "creators": [{
            "creatorType": "author",
            "firstName": "John Claudius",
            "lastName": "Loudon"
        }],
        "abstractNote": "",
        "series": "",
        "seriesNumber": "",
        "volume": "",
        "numberOfVolumes": "",
        "edition": "",
        "place": "",
        "publisher": "",
        "date": "1811",
        "numPages": "198",
        "language": "en",
        "ISBN": "",
        "shortTitle": "Designs for laying out Farms and farm-buildings in the Scotch style; adapted to England",
        "url": "",
        "accessDate": "",
        "archive": "",
        "archiveLocation": "",
        "libraryCatalog": "Google Books",
        "callNumber": "",
        "rights": "",
        "extra": "",
        "tags": [],
        "collections": ["8ZQTCFH5"],
        "relations": {},
        "dateAdded": "2018-09-14T21:02:26Z",
        "dateModified": "2018-09-14T21:02:26Z"
    }
}, {
    "title": "An encyclopædia of cottage, farm, and villa architecture and furniture",
    "data": {
        "key": "BBGI6XAZ",
        "version": 3235,
        "itemType": "book",
        "title": "An encyclopædia of cottage, farm, and villa architecture and furniture: containing numerous designs for dwellings from the cottage to the villa including farm houses, farmeries, and other agricultural buildings, several designs for country inns, public houses, and parochial schools, with the requisite fittings-up fixtures and furniture ; and appropriate offices, gardens and garden scenery ;  each design accompanied by analytical and critical marks illustrative of the principles of archtiectural science and taste on whihc it is composed",
        "creators": [{
            "creatorType": "author",
            "firstName": "J. C.",
            "lastName": "Loudon"
        }],
        "abstractNote": "",
        "series": "",
        "seriesNumber": "",
        "volume": "",
        "numberOfVolumes": "",
        "edition": "",
        "place": "London",
        "publisher": "Longman, Rees, Orme, Brown, Green, & Longmans, and sold by John Weale, at the Architectural Library, High Holborn",
        "date": "1836",
        "numPages": "xx, 1136 p.",
        "language": "",
        "ISBN": "",
        "shortTitle": "An encyclopædia of cottage, farm, and villa architecture and furniture",
        "url": "https://catalog.hathitrust.org/Record/000607885",
        "accessDate": "2018-09-14T22:28:32Z",
        "archive": "",
        "archiveLocation": "",
        "libraryCatalog": "Hathi Trust",
        "callNumber": "",
        "rights": "",
        "extra": "",
        "tags": [{
            "tag": "Architecture, Domestic.",
            "type": 1
        }, {
            "tag": "Furniture.",
            "type": 1
        }],
        "collections": ["LMWECFU5"],
        "relations": {},
        "dateAdded": "2018-09-14T22:28:33Z",
        "dateModified": "2018-09-14T22:28:33Z"
    }
}, {
    "title": "Encyclopaedia of Gardening",
    "data": {
        "key": "LQWSPBNL",
        "version": 507,
        "itemType": "book",
        "title": "An encyclopaedia of gardening; comprising the theory and practice of horticulture, floriculture, arboriculture, and landscape-gardening, including all the latest improvements; a general history of gardening in all countries; and a statistical view of its present state, with suggestions for its future progress in the British Isles.",
        "creators": [{
            "creatorType": "author",
            "firstName": "J. C.",
            "lastName": "Loudon"
        }],
        "abstractNote": "",
        "series": "",
        "seriesNumber": "",
        "volume": "",
        "numberOfVolumes": "",
        "edition": "3d ed.",
        "place": "London :",
        "publisher": "Longman, Hurst, Rees, Orme, Brown, and Green,",
        "date": "1825",
        "numPages": "1272",
        "language": "",
        "ISBN": "",
        "shortTitle": "",
        "url": "https://www.biodiversitylibrary.org/bibliography/29708",
        "accessDate": "",
        "archive": "done",
        "archiveLocation": "",
        "libraryCatalog": "BHL",
        "callNumber": "",
        "rights": "",
        "extra": "LD: 9+",
        "tags": [],
        "collections": ["KXUA5LUF"],
        "relations": {},
        "dateAdded": "2018-03-26T14:32:39Z",
        "dateModified": "2018-03-26T14:34:56Z"
    }
}, {
    "title": "Faust",
    "data": {
        "key": "M5DRFLZ6",
        "version": 3238,
        "itemType": "book",
        "title": "Faust; a dramatic poem. Part II.",
        "creators": [{
            "creatorType": "author",
            "firstName": "Johann Wolfgang von",
            "lastName": "Goethe"
        }, {
            "creatorType": "author",
            "firstName": "Theodore",
            "lastName": "Martin"
        }],
        "abstractNote": "",
        "series": "Faust.2. Theil.English",
        "seriesNumber": "",
        "volume": "",
        "numberOfVolumes": "",
        "edition": "",
        "place": "Edinburgh, etc.",
        "publisher": "W. Blackwood and sons",
        "date": "1886",
        "numPages": "xiv, 307 p.",
        "language": "",
        "ISBN": "",
        "shortTitle": "",
        "url": "https://catalog.hathitrust.org/Record/100396742",
        "accessDate": "2018-09-14T22:29:55Z",
        "archive": "",
        "archiveLocation": "",
        "libraryCatalog": "Hathi Trust",
        "callNumber": "",
        "rights": "",
        "extra": "",
        "tags": [],
        "collections": ["LMWECFU5"],
        "relations": {},
        "dateAdded": "2018-09-14T22:29:55Z",
        "dateModified": "2018-09-14T22:29:55Z"
    }
}, {
    "title": "Forty Years of Landscape Architecture",
    "data": {
        "key": "A3YGCVT8",
        "version": 3241,
        "itemType": "book",
        "title": "Forty years of landscape architecture: Central Park [by] Frederick Law Olmsted, Sr.",
        "creators": [{
            "creatorType": "author",
            "firstName": "Frederick Law",
            "lastName": "Olmsted"
        }],
        "abstractNote": "",
        "series": "",
        "seriesNumber": "",
        "volume": "",
        "numberOfVolumes": "",
        "edition": "",
        "place": "Cambridge, Mass.,",
        "publisher": "MIT Press",
        "date": "[1973, c1928]",
        "numPages": "",
        "language": "",
        "ISBN": "978-0-262-15009-5",
        "shortTitle": "Forty years of landscape architecture",
        "url": "",
        "accessDate": "",
        "archive": "",
        "archiveLocation": "",
        "libraryCatalog": "",
        "callNumber": "",
        "rights": "",
        "extra": "",
        "tags": [],
        "collections": ["AYFZDCDI"],
        "relations": {},
        "dateAdded": "2018-09-14T22:31:30Z",
        "dateModified": "2018-09-14T22:31:30Z"
    }
}, {
    "title": "The Papers of Frederick Law Olmsted: Supplementary Series",
    "data": {
        "key": "MZXSPD66",
        "version": 3234,
        "itemType": "book",
        "title": "The Papers of Frederick Law Olmsted: Supplementary Series",
        "creators": [{
            "creatorType": "author",
            "firstName": "Frederick Law",
            "lastName": "Olmsted"
        }],
        "abstractNote": "",
        "series": "",
        "seriesNumber": "",
        "volume": "",
        "numberOfVolumes": "",
        "edition": "",
        "place": "Baltimore :",
        "publisher": "Johns Hopkins University Press,",
        "date": "c1997-",
        "numPages": "",
        "language": "",
        "ISBN": "978-0-8018-5532-0",
        "shortTitle": "",
        "url": "",
        "accessDate": "",
        "archive": "",
        "archiveLocation": "",
        "libraryCatalog": "",
        "callNumber": "",
        "rights": "",
        "extra": "",
        "tags": [],
        "collections": ["AYFZDCDI"],
        "relations": {},
        "dateAdded": "2018-09-14T22:13:09Z",
        "dateModified": "2018-09-14T22:13:48Z"
    }
}, {
    "title": "Frederick Law Olmsted and the Boston Park System",
    "data": {
        "key": "4VBIIC5X",
        "version": 3244,
        "itemType": "book",
        "title": "Frederick Law Olmsted and the Boston park system /",
        "creators": [{
            "creatorType": "author",
            "firstName": "Cynthia",
            "lastName": "Zaitzevsky"
        }],
        "abstractNote": "",
        "series": "",
        "seriesNumber": "",
        "volume": "",
        "numberOfVolumes": "",
        "edition": "",
        "place": "Cambridge, Mass. :",
        "publisher": "Harvard University Press,",
        "date": "1982.",
        "numPages": "",
        "language": "",
        "ISBN": "978-0-674-31830-4",
        "shortTitle": "",
        "url": "",
        "accessDate": "",
        "archive": "",
        "archiveLocation": "",
        "libraryCatalog": "",
        "callNumber": "",
        "rights": "",
        "extra": "",
        "tags": [],
        "collections": ["AYFZDCDI"],
        "relations": {},
        "dateAdded": "2018-09-14T22:32:26Z",
        "dateModified": "2018-09-14T22:32:26Z"
    }
}, {
    "title": "Frederick Law Olmsted : designing the American landscape",
    "data": {
        "key": "DAETT93Y",
        "version": 3168,
        "itemType": "book",
        "title": "Frederick Law Olmsted : designing the American landscape /",
        "creators": [{
            "creatorType": "author",
            "firstName": "Charles E.",
            "lastName": "Beveridge"
        }],
        "abstractNote": "",
        "series": "",
        "seriesNumber": "",
        "volume": "",
        "numberOfVolumes": "",
        "edition": "",
        "place": "New York :",
        "publisher": "Rizzoli,",
        "date": "1995.",
        "numPages": "",
        "language": "",
        "ISBN": "978-0-8478-1842-6",
        "shortTitle": "Frederick Law Olmsted",
        "url": "",
        "accessDate": "",
        "archive": "",
        "archiveLocation": "",
        "libraryCatalog": "",
        "callNumber": "",
        "rights": "",
        "extra": "",
        "tags": [],
        "collections": ["AYFZDCDI"],
        "relations": {},
        "dateAdded": "2018-09-14T21:04:31Z",
        "dateModified": "2018-09-14T21:04:31Z"
    }
}, {
    "title": "The fruits and fruit trees of America",
    "data": {
        "key": "7IBK9NAD",
        "version": 3247,
        "itemType": "book",
        "title": "The fruits and fruit trees of America. : [Supplementary material in Charles Darwin's copy].",
        "creators": [{
            "creatorType": "author",
            "firstName": "Charles",
            "lastName": "Darwin"
        }, {
            "creatorType": "author",
            "firstName": "Andrew Jackson",
            "lastName": "Downing"
        }],
        "abstractNote": "",
        "series": "",
        "seriesNumber": "",
        "volume": "Supplementary material in Darwin's copy",
        "numberOfVolumes": "",
        "edition": "",
        "place": "",
        "publisher": "",
        "date": "",
        "numPages": "6",
        "language": "",
        "ISBN": "",
        "shortTitle": "The fruits and fruit trees of America.",
        "url": "https://www.biodiversitylibrary.org/item/106254",
        "accessDate": "",
        "archive": "",
        "archiveLocation": "",
        "libraryCatalog": "",
        "callNumber": "",
        "rights": "",
        "extra": "",
        "tags": [],
        "collections": ["KXUA5LUF"],
        "relations": {},
        "dateAdded": "2018-09-14T22:37:50Z",
        "dateModified": "2018-09-14T22:37:50Z"
    }
}, {
    "title": "Gardener's Magazine",
    "data": {
        "key": "AUGAA3CC",
        "version": 3186,
        "itemType": "book",
        "title": "Horticultural register, and gardener's magazine.",
        "creators": [{
            "creatorType": "author",
            "firstName": "Joseph",
            "lastName": "Breck"
        }, {
            "creatorType": "author",
            "firstName": "Thomas Green",
            "lastName": "Fesseden"
        }, {
            "creatorType": "author",
            "firstName": "James E.",
            "lastName": "Teschemacher"
        }],
        "abstractNote": "",
        "series": "",
        "seriesNumber": "",
        "volume": "v.1 1835",
        "numberOfVolumes": "",
        "edition": "",
        "place": "Boston,",
        "publisher": "G. D. Barrett [etc.]",
        "date": "1835",
        "numPages": "508",
        "language": "",
        "ISBN": "",
        "shortTitle": "",
        "url": "https://www.biodiversitylibrary.org/item/78876",
        "accessDate": "",
        "archive": "",
        "archiveLocation": "",
        "libraryCatalog": "",
        "callNumber": "",
        "rights": "",
        "extra": "",
        "tags": [],
        "collections": ["KXUA5LUF"],
        "relations": {},
        "dateAdded": "2018-09-14T21:11:15Z",
        "dateModified": "2018-09-14T21:11:15Z"
    }
}, {
    "title": "Gardeners' Magazine of Botany",
    "data": {
        "key": "7PLTC32B",
        "version": 3174,
        "itemType": "book",
        "title": "Gardeners' magazine of botany, horticulture, floriculture, and natural science.",
        "creators": [],
        "abstractNote": "",
        "series": "",
        "seriesNumber": "",
        "volume": "v.3 (1851)",
        "numberOfVolumes": "",
        "edition": "",
        "place": "London :",
        "publisher": "William S. Orr and Co.,",
        "date": "1851",
        "numPages": "456",
        "language": "",
        "ISBN": "",
        "shortTitle": "",
        "url": "https://www.biodiversitylibrary.org/item/211948",
        "accessDate": "",
        "archive": "",
        "archiveLocation": "",
        "libraryCatalog": "",
        "callNumber": "",
        "rights": "",
        "extra": "",
        "tags": [],
        "collections": ["KXUA5LUF"],
        "relations": {},
        "dateAdded": "2018-09-14T21:07:16Z",
        "dateModified": "2018-09-14T21:07:16Z"
    }
}, {
    "title": "Gardening for Ladies",
    "data": {
        "key": "48N5N7QK",
        "version": 3250,
        "itemType": "book",
        "title": "Gardening for ladies, and, Companion to the flower-garden /",
        "creators": [{
            "creatorType": "author",
            "firstName": "",
            "lastName": "Loudon"
        }, {
            "creatorType": "author",
            "firstName": "",
            "lastName": "Loudon"
        }, {
            "creatorType": "author",
            "firstName": "A. J.",
            "lastName": "Downing"
        }],
        "abstractNote": "",
        "series": "",
        "seriesNumber": "",
        "volume": "1851",
        "numberOfVolumes": "",
        "edition": "2nd American, from the 3rd London ed. / edited by A.J. Downing.",
        "place": "New York :",
        "publisher": "John Wiley,",
        "date": "1851",
        "numPages": "444",
        "language": "",
        "ISBN": "",
        "shortTitle": "",
        "url": "https://www.biodiversitylibrary.org/item/48064",
        "accessDate": "",
        "archive": "",
        "archiveLocation": "",
        "libraryCatalog": "",
        "callNumber": "",
        "rights": "",
        "extra": "",
        "tags": [],
        "collections": ["KXUA5LUF"],
        "relations": {},
        "dateAdded": "2018-09-14T22:38:59Z",
        "dateModified": "2018-09-14T22:38:59Z"
    }
}, {
    "title": "Gardens in the Modern Landscape",
    "data": {
        "key": "QV6YG9AL",
        "version": 3177,
        "itemType": "book",
        "title": "Gardens in the modern landscape.",
        "creators": [{
            "creatorType": "author",
            "firstName": "Christopher",
            "lastName": "Tunnard"
        }],
        "abstractNote": "",
        "series": "",
        "seriesNumber": "",
        "volume": "",
        "numberOfVolumes": "",
        "edition": "2d rev. ed.",
        "place": "London,",
        "publisher": "Architectural Press,",
        "date": "1950",
        "numPages": "",
        "language": "",
        "ISBN": "",
        "shortTitle": "",
        "url": "",
        "accessDate": "",
        "archive": "",
        "archiveLocation": "",
        "libraryCatalog": "",
        "callNumber": "",
        "rights": "",
        "extra": "",
        "tags": [],
        "collections": ["AYFZDCDI"],
        "relations": {},
        "dateAdded": "2018-09-14T21:08:07Z",
        "dateModified": "2018-09-14T21:08:07Z"
    }
}, {
    "title": "Genera of North American Plants",
    "data": {
        "key": "Z33VHA4N",
        "version": 3180,
        "itemType": "webpage",
        "title": "The genera of North American plants",
        "creators": [{
            "creatorType": "author",
            "firstName": "Thomas",
            "lastName": "Nuttall"
        }, {
            "creatorType": "contributor",
            "firstName": "Biblioteca Digital del Real Jardin Botanico de",
            "lastName": "Madrid"
        }],
        "abstractNote": "",
        "websiteTitle": "Biodiversity Heritage Library",
        "websiteType": "",
        "date": "1818",
        "shortTitle": "",
        "url": "https://www.biodiversitylibrary.org/bibliography/74802",
        "accessDate": "",
        "language": "",
        "rights": "Creative Commons Attribution 3.0",
        "extra": "",
        "tags": [{
            "tag": "Algas",
            "type": 1
        }, {
            "tag": "America",
            "type": 1
        }, {
            "tag": "Angiospermas",
            "type": 1
        }, {
            "tag": "Flora",
            "type": 1
        }, {
            "tag": "Gimnospermas",
            "type": 1
        }, {
            "tag": "Pteridófitos",
            "type": 1
        }],
        "collections": ["KXUA5LUF"],
        "relations": {},
        "dateAdded": "2018-09-14T21:09:19Z",
        "dateModified": "2018-09-14T21:09:19Z"
    }
}, {
    "title": "Generelle Morphologie der Organismen",
    "data": {
        "key": "3RHX52RU",
        "version": 3253,
        "itemType": "book",
        "title": "Generelle morphologie der organismen. Allgemeine grundzüge der organischen formen-wissenschaft, mechanisch begründet durch die von Charles Darwin reformirte descendenztheorie,",
        "creators": [{
            "creatorType": "author",
            "firstName": "Ernst",
            "lastName": "Haeckel"
        }],
        "abstractNote": "",
        "series": "",
        "seriesNumber": "",
        "volume": "bd. 1",
        "numberOfVolumes": "",
        "edition": "",
        "place": "Berlin,",
        "publisher": "G. Reimer,",
        "date": "",
        "numPages": "626",
        "language": "",
        "ISBN": "",
        "shortTitle": "",
        "url": "https://www.biodiversitylibrary.org/item/22319",
        "accessDate": "",
        "archive": "",
        "archiveLocation": "",
        "libraryCatalog": "",
        "callNumber": "",
        "rights": "",
        "extra": "",
        "tags": [],
        "collections": ["KXUA5LUF"],
        "relations": {},
        "dateAdded": "2018-09-14T22:40:12Z",
        "dateModified": "2018-09-14T22:40:12Z"
    }
}, {
    "title": "George Perkins Marsh: Prophet of Conservation",
    "data": {
        "key": "C8FAHC3U",
        "version": 3183,
        "itemType": "book",
        "title": "George Perkins Marsh: Prophet of Conservation",
        "creators": [{
            "creatorType": "author",
            "firstName": "David",
            "lastName": "Lowenthal"
        }, {
            "creatorType": "author",
            "firstName": "William",
            "lastName": "Cronon"
        }],
        "abstractNote": "George Perkins Marsh (1801�1882) was the first to reveal the menace of environmental misuse, to explain its causes, and to prescribe reforms. David Lowenthal here offers fresh insights, from new sources, into Marsh�s career and shows his relevance today, in a book which has its roots in but wholly supersedes Lowenthal�s earlier biography George Perkins Marsh: Versatile Vermonter (1958). Marsh�s devotion to the repair of nature, to the concerns of working people, to women�s rights, and to historical stewardship resonate more than ever. His Vermont birthplace is now a national park chronicling American conservation, and the crusade he launched is now global. Marsh�s seminal book Man and Nature is famed for its ecological acumen. The clue to its inception lies in Marsh�s many-sided engagement in the life of his time. The broadest scholar of his day, he was an acclaimed linguist, lawyer, congressman, and renowned diplomat who served 25 years as U.S. envoy to Turkey and to Italy. He helped found and guide the Smithsonian Institution, shaped the Washington Monument, penned potent tracts on fisheries and on irrigation, spearheaded public science, art, and architecture. He wrote on camels and corporate corruption, Icelandic grammar and Alpine glaciers. His pungent and provocative letters illuminate life on both sides of the Atlantic. Like Darwin�s Origin of Species, Marsh�s Man and Nature marked the inception of a truly modern way of looking at the world, of taking care lest we irreversibly degrade the fabric of humanized nature we are bound to manage. Marsh�s ominous warnings inspired reforestation, watershed management, soil conservation, and nature protection in his day and ours. George Perkins Marsh: Prophet of Conservation was awarded the Association for American Geographers' 2000 J. B. Jackson Prize. The book was also on the shortlist for the first British Academy Book Prize, awarded in December 2001.",
        "series": "",
        "seriesNumber": "",
        "volume": "",
        "numberOfVolumes": "",
        "edition": "",
        "place": "Seattle, UNITED STATES",
        "publisher": "University of Washington Press",
        "date": "2009",
        "numPages": "",
        "language": "",
        "ISBN": "978-0-295-98985-3",
        "shortTitle": "George Perkins Marsh",
        "url": "http://ebookcentral.proquest.com/lib/uva/detail.action?docID=3444256",
        "accessDate": "2018-09-14T21:10:21Z",
        "archive": "",
        "archiveLocation": "",
        "libraryCatalog": "ProQuest Ebook Central",
        "callNumber": "",
        "rights": "",
        "extra": "",
        "tags": [{
            "tag": "Conservationists -- United States -- Biography.",
            "type": 1
        }, {
            "tag": "Marsh, George P. -- (George Perkins), -- 1801-1882.",
            "type": 1
        }, {
            "tag": "Statesmen -- United States -- Biography.",
            "type": 1
        }, {
            "tag": "United States -- Environmental conditions.",
            "type": 1
        }],
        "collections": ["H5M6T9ZH"],
        "relations": {},
        "dateAdded": "2018-09-14T21:10:21Z",
        "dateModified": "2018-09-14T21:10:21Z"
    }
}, {
    "title": "Greater Perfections",
    "data": {
        "key": "9X5H4SX3",
        "version": 3256,
        "itemType": "book",
        "title": "Greater perfections : the practice of garden theory /",
        "creators": [{
            "creatorType": "author",
            "firstName": "John Dixon",
            "lastName": "Hunt"
        }],
        "abstractNote": "",
        "series": "",
        "seriesNumber": "",
        "volume": "",
        "numberOfVolumes": "",
        "edition": "",
        "place": "Philadelphia :",
        "publisher": "University of Pennsylvania Press,",
        "date": "c2000.",
        "numPages": "",
        "language": "",
        "ISBN": "978-0-8122-3506-7",
        "shortTitle": "Greater perfections",
        "url": "",
        "accessDate": "",
        "archive": "",
        "archiveLocation": "",
        "libraryCatalog": "",
        "callNumber": "",
        "rights": "",
        "extra": "",
        "tags": [],
        "collections": ["AYFZDCDI"],
        "relations": {},
        "dateAdded": "2018-09-14T22:41:10Z",
        "dateModified": "2018-09-14T22:41:10Z"
    }
}, {
    "title": "Hortus Kewensis",
    "data": {
        "key": "YGABZTXF",
        "version": 3189,
        "itemType": "book",
        "title": "Hortus Kewensis, or, A catalogue of the plants cultivated in the Royal Botanic Garden at Kew /",
        "creators": [{
            "creatorType": "author",
            "firstName": "William",
            "lastName": "Aiton"
        }, {
            "creatorType": "author",
            "firstName": "Franz Andreas",
            "lastName": "Bauer"
        }, {
            "creatorType": "author",
            "firstName": "Georg Dionysius",
            "lastName": "Ehret"
        }, {
            "creatorType": "author",
            "firstName": "George",
            "lastName": "Nicol"
        }, {
            "creatorType": "author",
            "firstName": "James",
            "lastName": "Sowerby"
        }],
        "abstractNote": "",
        "series": "",
        "seriesNumber": "",
        "volume": "v.1",
        "numberOfVolumes": "",
        "edition": "",
        "place": "London :",
        "publisher": "Printed for George Nicol, Bookseller to his Majesty,",
        "date": "1789",
        "numPages": "532",
        "language": "",
        "ISBN": "",
        "shortTitle": "",
        "url": "https://www.biodiversitylibrary.org/item/23432",
        "accessDate": "",
        "archive": "",
        "archiveLocation": "",
        "libraryCatalog": "",
        "callNumber": "",
        "rights": "",
        "extra": "",
        "tags": [],
        "collections": ["KXUA5LUF"],
        "relations": {},
        "dateAdded": "2018-09-14T21:13:18Z",
        "dateModified": "2018-09-14T21:13:18Z"
    }
}, {
    "title": "Landscape into Cityscape",
    "data": {
        "key": "MC2WINAX",
        "version": 3259,
        "itemType": "book",
        "title": "Landscape into cityscape; Frederick Law Olmsted's plans for a greater New York City.",
        "creators": [{
            "creatorType": "author",
            "firstName": "Frederick Law",
            "lastName": "Olmsted"
        }],
        "abstractNote": "",
        "series": "",
        "seriesNumber": "",
        "volume": "",
        "numberOfVolumes": "",
        "edition": "",
        "place": "Ithaca, N.Y.,",
        "publisher": "Cornell University Press",
        "date": "[1967, c1967]",
        "numPages": "",
        "language": "",
        "ISBN": "",
        "shortTitle": "",
        "url": "",
        "accessDate": "",
        "archive": "",
        "archiveLocation": "",
        "libraryCatalog": "",
        "callNumber": "",
        "rights": "",
        "extra": "",
        "tags": [],
        "collections": ["AYFZDCDI"],
        "relations": {},
        "dateAdded": "2018-09-14T22:41:41Z",
        "dateModified": "2018-09-14T22:41:41Z"
    }
}, {
    "title": "Loudon and the Landscape: From Country Seat to Metropolis",
    "data": {
        "key": "P9DPFA2J",
        "version": 3192,
        "itemType": "book",
        "title": "Loudon and the landscape : from country seat to metropolis, 1783-1843 /",
        "creators": [{
            "creatorType": "author",
            "firstName": "Melanie Louise",
            "lastName": "Simo"
        }],
        "abstractNote": "",
        "series": "",
        "seriesNumber": "",
        "volume": "",
        "numberOfVolumes": "",
        "edition": "",
        "place": "New Haven :",
        "publisher": "Yale University Press,",
        "date": "c1988.",
        "numPages": "",
        "language": "",
        "ISBN": "978-0-300-03745-6",
        "shortTitle": "Loudon and the landscape",
        "url": "",
        "accessDate": "",
        "archive": "",
        "archiveLocation": "",
        "libraryCatalog": "",
        "callNumber": "",
        "rights": "",
        "extra": "",
        "tags": [],
        "collections": ["AYFZDCDI"],
        "relations": {},
        "dateAdded": "2018-09-14T21:13:50Z",
        "dateModified": "2018-09-14T21:13:50Z"
    }
}, {
    "title": "Loudon's Hortus Britannicus",
    "data": {
        "key": "TXJYQH8U",
        "version": 507,
        "itemType": "book",
        "title": "Loudon's Hortus britannicus : a catalogue of all the plants indigenous, cultivated in, or introduced to Britain. Part I. The Linnaean arrangement : part II. The Jussieuean arrangement /",
        "creators": [{
            "creatorType": "author",
            "firstName": "J. C.",
            "lastName": "Loudon"
        }],
        "abstractNote": "",
        "series": "",
        "seriesNumber": "",
        "volume": "",
        "numberOfVolumes": "",
        "edition": "[3rd ed.]",
        "place": "London :",
        "publisher": "Printed for Longman, Rees, Orme, Brown, and Green & Longman,",
        "date": "1839",
        "numPages": "762",
        "language": "",
        "ISBN": "",
        "shortTitle": "Loudon's Hortus britannicus",
        "url": "https://www.biodiversitylibrary.org/bibliography/68944",
        "accessDate": "",
        "archive": "done",
        "archiveLocation": "",
        "libraryCatalog": "BHL",
        "callNumber": "",
        "rights": "",
        "extra": "LD: 9+",
        "tags": [],
        "collections": ["KXUA5LUF"],
        "relations": {},
        "dateAdded": "2018-03-26T14:33:54Z",
        "dateModified": "2018-03-26T14:36:57Z"
    }
}, {
    "title": "Man and Nature",
    "data": {
        "key": "2R3ZNGIB",
        "version": 3262,
        "itemType": "book",
        "title": "Man and Nature: The earth as modified by human action / by George P. Marsh.",
        "creators": [{
            "creatorType": "author",
            "firstName": "George Perkins",
            "lastName": "Marsh"
        }],
        "abstractNote": "",
        "series": "",
        "seriesNumber": "",
        "volume": "1874 edition",
        "numberOfVolumes": "",
        "edition": "A new ed. of Man and nature.",
        "place": "New York :",
        "publisher": "Scribner, Armstrong & Co.,",
        "date": "1907",
        "numPages": "690",
        "language": "",
        "ISBN": "",
        "shortTitle": "",
        "url": "https://www.biodiversitylibrary.org/item/48814",
        "accessDate": "",
        "archive": "",
        "archiveLocation": "",
        "libraryCatalog": "",
        "callNumber": "",
        "rights": "",
        "extra": "",
        "tags": [],
        "collections": ["KXUA5LUF"],
        "relations": {},
        "dateAdded": "2018-09-14T22:44:40Z",
        "dateModified": "2018-09-14T22:44:57Z"
    }
}, {
    "title": "Mount Auburn",
    "data": {
        "key": "CHEHRF2L",
        "version": 3213,
        "itemType": "book",
        "title": "Silent city on a hill : picturesque landscapes of memory and Boston's Mount Auburn Cemetery /",
        "creators": [{
            "creatorType": "author",
            "firstName": "Blanche M. G.",
            "lastName": "Linden"
        }],
        "abstractNote": "",
        "series": "",
        "seriesNumber": "",
        "volume": "",
        "numberOfVolumes": "",
        "edition": "Rev. and expanded ed.",
        "place": "Amherst :",
        "publisher": "University of Massachusetts Press in association with Library of American Landscape History,",
        "date": "c2007.",
        "numPages": "",
        "language": "",
        "ISBN": "978-1-55849-571-5",
        "shortTitle": "Silent city on a hill",
        "url": "",
        "accessDate": "",
        "archive": "",
        "archiveLocation": "",
        "libraryCatalog": "",
        "callNumber": "",
        "rights": "",
        "extra": "",
        "tags": [],
        "collections": ["AYFZDCDI"],
        "relations": {},
        "dateAdded": "2018-09-14T21:35:53Z",
        "dateModified": "2018-09-14T21:35:53Z"
    }
}, {
    "title": "Mount Auburn Illustrated",
    "data": {
        "key": "IVGXLXFA",
        "version": 413,
        "itemType": "book",
        "title": "Green-wood illustrated: in highly finished line engraving, from drawings taken on the spot",
        "creators": [{
            "creatorType": "author",
            "firstName": "N.",
            "lastName": "Cleaveland"
        }, {
            "creatorType": "author",
            "firstName": "James",
            "lastName": "Smillie"
        }, {
            "creatorType": "author",
            "firstName": "Seymour B.",
            "lastName": "Durst"
        }],
        "abstractNote": "",
        "series": "",
        "seriesNumber": "",
        "volume": "",
        "numberOfVolumes": "",
        "edition": "",
        "place": "New York",
        "publisher": "Published by R. Martin",
        "date": "1847",
        "numPages": "[1] leaf, [2], 93, [7] p., [19] leaves of plates",
        "language": "",
        "ISBN": "",
        "shortTitle": "Green-wood illustrated",
        "url": "https://catalog.hathitrust.org/Record/100854692",
        "accessDate": "2018-03-23T21:04:30Z",
        "archive": "done",
        "archiveLocation": "",
        "libraryCatalog": "Hathi Trust",
        "callNumber": "",
        "rights": "",
        "extra": "LD: 9",
        "tags": [{
            "tag": "Brooklyn (New York)",
            "type": 1
        }, {
            "tag": "Cemeteries",
            "type": 1
        }, {
            "tag": "Greenwood Cemetery (Brooklyn, N.Y.)",
            "type": 1
        }, {
            "tag": "NNC",
            "type": 1
        }, {
            "tag": "New York (State)",
            "type": 1
        }, {
            "tag": "Signatures (Provenance)",
            "type": 1
        }, {
            "tag": "Stamps (Provenance)",
            "type": 1
        }, {
            "tag": "rbprov",
            "type": 1
        }],
        "collections": ["LMWECFU5"],
        "relations": {},
        "dateAdded": "2018-03-23T21:04:30Z",
        "dateModified": "2018-03-24T13:20:18Z"
    }
}, {
    "title": "New England Farmer",
    "data": {
        "key": "4HFGKZNV",
        "version": 3195,
        "itemType": "book",
        "title": "The New England farmer.",
        "creators": [],
        "abstractNote": "",
        "series": "",
        "seriesNumber": "",
        "volume": "v.1 1822-23",
        "numberOfVolumes": "",
        "edition": "",
        "place": "Boston :",
        "publisher": "Thomas W. Shepard,",
        "date": "1822",
        "numPages": "436",
        "language": "",
        "ISBN": "",
        "shortTitle": "",
        "url": "https://www.biodiversitylibrary.org/item/77782",
        "accessDate": "",
        "archive": "",
        "archiveLocation": "",
        "libraryCatalog": "",
        "callNumber": "",
        "rights": "",
        "extra": "",
        "tags": [],
        "collections": ["KXUA5LUF"],
        "relations": {},
        "dateAdded": "2018-09-14T21:14:56Z",
        "dateModified": "2018-09-14T21:14:56Z"
    }
}, {
    "title": "New York Daily Times",
    "data": {
        "key": "AWDAYYE7",
        "version": 3198,
        "itemType": "webpage",
        "title": "New York Daily Times (1851-1857); New York, N.Y. - ProQuest",
        "creators": [],
        "abstractNote": "",
        "websiteTitle": "",
        "websiteType": "",
        "date": "",
        "shortTitle": "",
        "url": "http://search.proquest.com/publication/11558",
        "accessDate": "2018-09-14T21:24:08Z",
        "language": "en",
        "rights": "",
        "extra": "",
        "tags": [],
        "collections": ["HS3Y7LBL"],
        "relations": {},
        "dateAdded": "2018-09-14T21:24:08Z",
        "dateModified": "2018-09-14T21:24:08Z"
    }
}, {
    "title": "Observations on Landscape Gardening",
    "data": {
        "key": "G2PCCJ6A",
        "version": 2740,
        "itemType": "book",
        "title": "Rural Residences: Consisting of a Series of Designs for Cottages, Decorated Cottages, Small Villas, and Other Ornamental Buildings, Accompanied by Hints on Situation, Construction, Arrangement and Decoration in the Theory & Practice of Rural Architecture; Interspersed with Some Observations on Landscape Gardening",
        "creators": [{
            "creatorType": "author",
            "firstName": "John Buonarotti",
            "lastName": "Papworth"
        }],
        "abstractNote": "",
        "series": "",
        "seriesNumber": "",
        "volume": "",
        "numberOfVolumes": "",
        "edition": "",
        "place": "",
        "publisher": "R. Ackerman...by J. Diggens",
        "date": "1818",
        "numPages": "176",
        "language": "en",
        "ISBN": "",
        "shortTitle": "Rural Residences",
        "url": "",
        "accessDate": "",
        "archive": "",
        "archiveLocation": "",
        "libraryCatalog": "Google Books",
        "callNumber": "",
        "rights": "",
        "extra": "Google-Books-ID: yFtDAQAAMAAJ",
        "tags": [],
        "collections": [],
        "relations": {},
        "dateAdded": "2018-04-26T18:08:25Z",
        "dateModified": "2018-04-26T18:08:25Z"
    }
}, {
    "title": "Observations on the Theory and Practice of Landscape Gardening",
    "data": {
        "key": "ATZTLCNK",
        "version": 2814,
        "itemType": "book",
        "title": "Observations on the theory and practice of landscape gardening : including some remarks on Grecian and Gothic architecture, collected from various manuscripts, in the possession of the different noblemen and gentlemen, for whose use they were originally written : the whole tending to establish fixed principles in the respective arts /",
        "creators": [{
            "creatorType": "author",
            "firstName": "Humphry",
            "lastName": "Repton"
        }, {
            "creatorType": "author",
            "firstName": "J. Adey",
            "lastName": "Repton"
        }],
        "abstractNote": "",
        "series": "",
        "seriesNumber": "",
        "volume": "",
        "numberOfVolumes": "",
        "edition": "",
        "place": "London :",
        "publisher": "Printed by T. Bensley ... for J. Taylor ...,",
        "date": "1805",
        "numPages": "328",
        "language": "",
        "ISBN": "",
        "shortTitle": "Observations on the theory and practice of landscape gardening",
        "url": "https://www.biodiversitylibrary.org/bibliography/44819",
        "accessDate": "",
        "archive": "done",
        "archiveLocation": "",
        "libraryCatalog": "BHL",
        "callNumber": "",
        "rights": "",
        "extra": "LD: 7",
        "tags": [],
        "collections": ["KXUA5LUF", "Y4KN4ME8"],
        "relations": {},
        "dateAdded": "2018-03-26T15:46:23Z",
        "dateModified": "2018-03-28T21:52:04Z"
    }
}, {
    "title": "On the Growth of Plants in Closely Glazed Cases",
    "data": {
        "key": "Z7CMESGY",
        "version": 3265,
        "itemType": "book",
        "title": "On the growth of plants in closely glazed cases /",
        "creators": [{
            "creatorType": "author",
            "firstName": "N. B.",
            "lastName": "Ward"
        }],
        "abstractNote": "",
        "series": "",
        "seriesNumber": "",
        "volume": "",
        "numberOfVolumes": "",
        "edition": "2d ed.",
        "place": "London :",
        "publisher": "J. Van Voorst,",
        "date": "1852",
        "numPages": "170",
        "language": "",
        "ISBN": "",
        "shortTitle": "",
        "url": "https://www.biodiversitylibrary.org/item/230860",
        "accessDate": "",
        "archive": "",
        "archiveLocation": "",
        "libraryCatalog": "",
        "callNumber": "",
        "rights": "",
        "extra": "",
        "tags": [],
        "collections": ["KXUA5LUF"],
        "relations": {},
        "dateAdded": "2018-09-14T22:51:07Z",
        "dateModified": "2018-09-14T22:51:07Z"
    }
}, {
    "title": "Paxton's Magazine of Botany",
    "data": {
        "key": "2IMXEQPG",
        "version": 3201,
        "itemType": "book",
        "title": "Paxton's magazine of botany, and register of flowering plants.",
        "creators": [{
            "creatorType": "author",
            "firstName": "C. J.",
            "lastName": "Fleming"
        }, {
            "creatorType": "author",
            "firstName": "S.",
            "lastName": "Holden"
        }, {
            "creatorType": "author",
            "firstName": "Thomas Orlando Sheldon",
            "lastName": "Jewitt"
        }, {
            "creatorType": "author",
            "firstName": "Joseph",
            "lastName": "Paxton"
        }, {
            "creatorType": "author",
            "firstName": "Frederick William",
            "lastName": "Smith"
        }, {
            "creatorType": "author",
            "firstName": "Bradbury &",
            "lastName": "Evans"
        }],
        "abstractNote": "",
        "series": "",
        "seriesNumber": "",
        "volume": "",
        "numberOfVolumes": "",
        "edition": "",
        "place": "London;",
        "publisher": "Orr and Smith [etc.].",
        "date": "1834",
        "numPages": "400",
        "language": "",
        "ISBN": "",
        "shortTitle": "",
        "url": "https://www.biodiversitylibrary.org/bibliography/106451",
        "accessDate": "",
        "archive": "",
        "archiveLocation": "",
        "libraryCatalog": "",
        "callNumber": "",
        "rights": "",
        "extra": "",
        "tags": [],
        "collections": ["KXUA5LUF"],
        "relations": {},
        "dateAdded": "2018-09-14T21:25:07Z",
        "dateModified": "2018-09-14T21:25:07Z"
    }
}, {
    "title": "People's Parks: The Design and Development of Victorian Parks in Britain",
    "data": {
        "key": "IFF94CFB",
        "version": 3210,
        "itemType": "book",
        "title": "People's parks : the design and development of Victorian parks  in Britain /",
        "creators": [{
            "creatorType": "author",
            "firstName": "Hazel",
            "lastName": "Conway"
        }],
        "abstractNote": "",
        "series": "",
        "seriesNumber": "",
        "volume": "",
        "numberOfVolumes": "",
        "edition": "",
        "place": "Cambridge [England] ;",
        "publisher": "Cambridge University Press,",
        "date": "1991.",
        "numPages": "",
        "language": "",
        "ISBN": "978-0-521-39070-5",
        "shortTitle": "People's parks",
        "url": "",
        "accessDate": "",
        "archive": "",
        "archiveLocation": "",
        "libraryCatalog": "",
        "callNumber": "",
        "rights": "",
        "extra": "",
        "tags": [],
        "collections": ["AYFZDCDI"],
        "relations": {},
        "dateAdded": "2018-09-14T21:29:27Z",
        "dateModified": "2018-09-14T21:29:27Z"
    }
}, {
    "title": "Putnam's Magazine",
    "data": {
        "key": "J46M8YAW",
        "version": 3204,
        "itemType": "journalArticle",
        "title": "Putnam's magazine.",
        "creators": [],
        "abstractNote": "",
        "publicationTitle": "",
        "volume": "",
        "issue": "",
        "pages": "",
        "date": "1853-1870",
        "series": "",
        "seriesTitle": "",
        "seriesText": "",
        "journalAbbreviation": "",
        "language": "",
        "DOI": "",
        "ISSN": "",
        "shortTitle": "",
        "url": "https://catalog.hathitrust.org/Record/100163659",
        "accessDate": "2018-09-14T21:26:50Z",
        "archive": "",
        "archiveLocation": "",
        "libraryCatalog": "Hathi Trust",
        "callNumber": "",
        "rights": "",
        "extra": "",
        "tags": [],
        "collections": ["LMWECFU5"],
        "relations": {},
        "dateAdded": "2018-09-14T21:26:50Z",
        "dateModified": "2018-09-14T21:26:50Z"
    }
}, {
    "title": "Rural Essays",
    "data": {
        "key": "DY68ZPVU",
        "version": 3268,
        "itemType": "book",
        "title": "Rural essays.",
        "creators": [{
            "creatorType": "author",
            "firstName": "A. J.",
            "lastName": "Downing"
        }, {
            "creatorType": "author",
            "firstName": "Fredrika",
            "lastName": "Bremer"
        }, {
            "creatorType": "author",
            "firstName": "George William",
            "lastName": "Curtis"
        }],
        "abstractNote": "",
        "series": "",
        "seriesNumber": "",
        "volume": "",
        "numberOfVolumes": "",
        "edition": "",
        "place": "New York,",
        "publisher": "G.P. Putnam",
        "date": "1853",
        "numPages": "658",
        "language": "",
        "ISBN": "",
        "shortTitle": "",
        "url": "https://www.biodiversitylibrary.org/bibliography/54907",
        "accessDate": "",
        "archive": "",
        "archiveLocation": "",
        "libraryCatalog": "",
        "callNumber": "",
        "rights": "",
        "extra": "",
        "tags": [],
        "collections": ["KXUA5LUF"],
        "relations": {},
        "dateAdded": "2018-09-14T22:52:56Z",
        "dateModified": "2018-09-14T22:52:56Z"
    }
}, {
    "title": "Self-instruction for Young Gardeners, Foresters, Bailiffs, Land-Stewards, and Farmers",
    "data": {
        "key": "LBQAWP6B",
        "version": 3207,
        "itemType": "book",
        "title": "Self-instruction for young gardeners, foresters, bailiffs, land-stewards, and farmers; in arithmetic and book-keeping, geometry, mensuration, and practical trigonometry, mechanics, hydrostatics, and hydraulics, land-surveying, levelling, planning, and mapping, architectural drawing, and isometrical projection and perspective: with examples, showing their application to horticultural and agricultural purposes.",
        "creators": [{
            "creatorType": "author",
            "firstName": "J. C.",
            "lastName": "Loudon"
        }],
        "abstractNote": "",
        "series": "",
        "seriesNumber": "",
        "volume": "",
        "numberOfVolumes": "",
        "edition": "",
        "place": "London",
        "publisher": "Longman, Brown, Green, and Longmans",
        "date": "1845",
        "numPages": "lii, 240 p.",
        "language": "",
        "ISBN": "",
        "shortTitle": "Self-instruction for young gardeners, foresters, bailiffs, land-stewards, and farmers; in arithmetic and book-keeping, geometry, mensuration, and practical trigonometry, mechanics, hydrostatics, and hydraulics, land-surveying, levelling, planning, and mapping, architectural drawing, and isometrical projection and perspective",
        "url": "https://catalog.hathitrust.org/Record/100123967",
        "accessDate": "2018-09-14T21:28:17Z",
        "archive": "",
        "archiveLocation": "",
        "libraryCatalog": "Hathi Trust",
        "callNumber": "",
        "rights": "",
        "extra": "",
        "tags": [{
            "tag": "Agricultural mathematics.",
            "type": 1
        }, {
            "tag": "Mathematics.",
            "type": 1
        }],
        "collections": ["LMWECFU5"],
        "relations": {},
        "dateAdded": "2018-09-14T21:28:17Z",
        "dateModified": "2018-09-14T21:28:17Z"
    }
}, {
    "title": "Silent city on a hill : picturesque landscapes of memory and Boston's Mount Auburn Cemetery",
    "data": {
        "key": "CHEHRF2L",
        "version": 3213,
        "itemType": "book",
        "title": "Silent city on a hill : picturesque landscapes of memory and Boston's Mount Auburn Cemetery /",
        "creators": [{
            "creatorType": "author",
            "firstName": "Blanche M. G.",
            "lastName": "Linden"
        }],
        "abstractNote": "",
        "series": "",
        "seriesNumber": "",
        "volume": "",
        "numberOfVolumes": "",
        "edition": "Rev. and expanded ed.",
        "place": "Amherst :",
        "publisher": "University of Massachusetts Press in association with Library of American Landscape History,",
        "date": "c2007.",
        "numPages": "",
        "language": "",
        "ISBN": "978-1-55849-571-5",
        "shortTitle": "Silent city on a hill",
        "url": "",
        "accessDate": "",
        "archive": "",
        "archiveLocation": "",
        "libraryCatalog": "",
        "callNumber": "",
        "rights": "",
        "extra": "",
        "tags": [],
        "collections": ["AYFZDCDI"],
        "relations": {},
        "dateAdded": "2018-09-14T21:35:53Z",
        "dateModified": "2018-09-14T21:35:53Z"
    }
}, {
    "title": "The Architecture of Country Houses",
    "data": {
        "key": "AZSYFMSG",
        "version": 3216,
        "itemType": "book",
        "title": "The architecture of country houses: including designs for cottages, farm houses, and villas, with remarks on interiors, furniture, and the best modes of warming and ventilating",
        "creators": [{
            "creatorType": "author",
            "firstName": "A. J.",
            "lastName": "Downing"
        }, {
            "creatorType": "author",
            "firstName": "Alexander",
            "lastName": "Anderson"
        }],
        "abstractNote": "",
        "series": "County houses",
        "seriesNumber": "",
        "volume": "",
        "numberOfVolumes": "",
        "edition": "",
        "place": "New York : Philadelphia",
        "publisher": "D. Appleton & Company, 200 Broadway ; Geo S. Appleton, 164 Chestnut-Street",
        "date": "1851",
        "numPages": "x, 484 p.. [34] leaves of plates",
        "language": "",
        "ISBN": "",
        "shortTitle": "The architecture of country houses",
        "url": "https://catalog.hathitrust.org/Record/010668308",
        "accessDate": "2018-09-14T21:52:29Z",
        "archive": "",
        "archiveLocation": "",
        "libraryCatalog": "Hathi Trust",
        "callNumber": "",
        "rights": "",
        "extra": "",
        "tags": [{
            "tag": "Architecture",
            "type": 1
        }, {
            "tag": "Domestic.",
            "type": 1
        }],
        "collections": ["LMWECFU5"],
        "relations": {},
        "dateAdded": "2018-09-14T21:52:29Z",
        "dateModified": "2018-09-14T21:52:29Z"
    }
}, {
    "title": "The English Flower Garden",
    "data": {
        "key": "PCSI9RG7",
        "version": 3271,
        "itemType": "book",
        "title": "The English flower garden : style position & arrangement ; followed by a description of all the best plants for it, their culture and arrangement /",
        "creators": [{
            "creatorType": "author",
            "firstName": "W.",
            "lastName": "Robinson"
        }, {
            "creatorType": "author",
            "firstName": "",
            "lastName": "John Murray (Firm)"
        }, {
            "creatorType": "author",
            "firstName": "",
            "lastName": "R. & R. Clark (Firm)"
        }],
        "abstractNote": "",
        "series": "",
        "seriesNumber": "",
        "volume": "",
        "numberOfVolumes": "",
        "edition": "Third edition.",
        "place": "London, [England] :",
        "publisher": "John Murray,",
        "date": "",
        "numPages": "782",
        "language": "",
        "ISBN": "",
        "shortTitle": "The English flower garden",
        "url": "https://www.biodiversitylibrary.org/item/187083",
        "accessDate": "",
        "archive": "",
        "archiveLocation": "",
        "libraryCatalog": "",
        "callNumber": "",
        "rights": "",
        "extra": "",
        "tags": [],
        "collections": ["KXUA5LUF"],
        "relations": {},
        "dateAdded": "2018-09-14T22:57:09Z",
        "dateModified": "2018-09-14T22:57:09Z"
    }
}, {
    "title": "The Excursion: A Poem",
    "data": {
        "key": "LSHLYKCC",
        "version": 3274,
        "itemType": "book",
        "title": "The excursion: a poem",
        "creators": [{
            "creatorType": "author",
            "firstName": "William",
            "lastName": "Wordsworth"
        }],
        "abstractNote": "",
        "series": "",
        "seriesNumber": "",
        "volume": "",
        "numberOfVolumes": "",
        "edition": "",
        "place": "London",
        "publisher": "Moxon",
        "date": "1853",
        "numPages": "xii, 374 p.",
        "language": "",
        "ISBN": "",
        "shortTitle": "The excursion",
        "url": "https://catalog.hathitrust.org/Record/000779248",
        "accessDate": "2018-09-14T22:57:40Z",
        "archive": "",
        "archiveLocation": "",
        "libraryCatalog": "Hathi Trust",
        "callNumber": "",
        "rights": "",
        "extra": "",
        "tags": [],
        "collections": ["LMWECFU5"],
        "relations": {},
        "dateAdded": "2018-09-14T22:57:40Z",
        "dateModified": "2018-09-14T22:57:40Z"
    }
}, {
    "title": "The Experience of Place",
    "data": {
        "key": "2CZKUQ2T",
        "version": 3219,
        "itemType": "book",
        "title": "The experience of place /",
        "creators": [{
            "creatorType": "author",
            "firstName": "Tony",
            "lastName": "Hiss"
        }],
        "abstractNote": "",
        "series": "",
        "seriesNumber": "",
        "volume": "",
        "numberOfVolumes": "",
        "edition": "1st Vintage Books ed.",
        "place": "New York :",
        "publisher": "Vintage Books,",
        "date": "1991.",
        "numPages": "",
        "language": "",
        "ISBN": "978-0-679-73594-6",
        "shortTitle": "",
        "url": "",
        "accessDate": "",
        "archive": "",
        "archiveLocation": "",
        "libraryCatalog": "",
        "callNumber": "",
        "rights": "",
        "extra": "",
        "tags": [],
        "collections": ["AYFZDCDI"],
        "relations": {},
        "dateAdded": "2018-09-14T21:53:36Z",
        "dateModified": "2018-09-14T21:53:36Z"
    }
}, {
    "title": "The Floricultural Cabinet",
    "data": {
        "key": "RAWYISIC",
        "version": 3222,
        "itemType": "book",
        "title": "The Floricultural Cabinet and Florist's Magazine.",
        "creators": [],
        "abstractNote": "",
        "series": "",
        "seriesNumber": "",
        "volume": "",
        "numberOfVolumes": "",
        "edition": "",
        "place": "London.",
        "publisher": "",
        "date": "",
        "numPages": "358",
        "language": "",
        "ISBN": "",
        "shortTitle": "",
        "url": "https://www.biodiversitylibrary.org/bibliography/15954",
        "accessDate": "",
        "archive": "",
        "archiveLocation": "",
        "libraryCatalog": "",
        "callNumber": "",
        "rights": "",
        "extra": "",
        "tags": [],
        "collections": ["KXUA5LUF"],
        "relations": {},
        "dateAdded": "2018-09-14T21:54:17Z",
        "dateModified": "2018-09-14T21:54:17Z"
    }
}, {
    "title": "The Formal Garden in England",
    "data": {
        "key": "D25LP77T",
        "version": 410,
        "itemType": "book",
        "title": "The formal garden in England",
        "creators": [{
            "creatorType": "author",
            "firstName": "Reginald Theodore",
            "lastName": "Blomfield"
        }, {
            "creatorType": "author",
            "firstName": "F. Inigo.",
            "lastName": "Thomas"
        }],
        "abstractNote": "",
        "series": "",
        "seriesNumber": "",
        "volume": "",
        "numberOfVolumes": "",
        "edition": "",
        "place": "London",
        "publisher": "Macmillian",
        "date": "1892",
        "numPages": "xii, 244 p.",
        "language": "",
        "ISBN": "",
        "shortTitle": "",
        "url": "https://catalog.hathitrust.org/Record/008692359",
        "accessDate": "2018-03-23T20:36:44Z",
        "archive": "done",
        "archiveLocation": "",
        "libraryCatalog": "Hathi Trust",
        "callNumber": "",
        "rights": "",
        "extra": "BBR",
        "tags": [{
            "tag": "England.",
            "type": 1
        }, {
            "tag": "Landscape architecture",
            "type": 1
        }],
        "collections": ["LMWECFU5"],
        "relations": {},
        "dateAdded": "2018-03-23T20:36:44Z",
        "dateModified": "2018-03-24T13:06:14Z"
    }
}, {
    "title": "The Green-House Companion",
    "data": {
        "key": "NRTTE45V",
        "version": 3277,
        "itemType": "book",
        "title": "The green-house companion;",
        "creators": [{
            "creatorType": "author",
            "firstName": "J. C.",
            "lastName": "Loudon"
        }],
        "abstractNote": "",
        "series": "",
        "seriesNumber": "",
        "volume": "",
        "numberOfVolumes": "",
        "edition": "3d ed.",
        "place": "London,",
        "publisher": "Whittaker, Treacher, and co.,",
        "date": "",
        "numPages": "430",
        "language": "",
        "ISBN": "",
        "shortTitle": "",
        "url": "https://www.biodiversitylibrary.org/item/138581",
        "accessDate": "",
        "archive": "",
        "archiveLocation": "",
        "libraryCatalog": "",
        "callNumber": "",
        "rights": "",
        "extra": "",
        "tags": [],
        "collections": ["KXUA5LUF"],
        "relations": {},
        "dateAdded": "2018-09-14T22:58:14Z",
        "dateModified": "2018-09-14T22:58:14Z"
    }
}, {
    "title": "The Holy Bible",
    "data": {
        "key": "TAQID7F9",
        "version": 3225,
        "itemType": "book",
        "title": "The Holy Bible",
        "creators": [],
        "abstractNote": "",
        "series": "",
        "seriesNumber": "",
        "volume": "",
        "numberOfVolumes": "",
        "edition": "",
        "place": "Phila.",
        "publisher": "",
        "date": "1830",
        "numPages": "1 v.",
        "language": "",
        "ISBN": "",
        "shortTitle": "",
        "url": "https://catalog.hathitrust.org/Record/001399949",
        "accessDate": "2018-09-14T21:55:31Z",
        "archive": "",
        "archiveLocation": "",
        "libraryCatalog": "Hathi Trust",
        "callNumber": "",
        "rights": "",
        "extra": "",
        "tags": [],
        "collections": ["LMWECFU5"],
        "relations": {},
        "dateAdded": "2018-09-14T21:55:31Z",
        "dateModified": "2018-09-14T21:55:31Z"
    }
}, {
    "title": "The Horticulturist",
    "data": {
        "key": "EYC4YPA2",
        "version": 507,
        "itemType": "book",
        "title": "The horticulturist;",
        "creators": [{
            "creatorType": "author",
            "firstName": "J. C.",
            "lastName": "Loudon"
        }],
        "abstractNote": "",
        "series": "",
        "seriesNumber": "",
        "volume": "",
        "numberOfVolumes": "",
        "edition": "",
        "place": "London,",
        "publisher": "W. S. Orr & co.,",
        "date": "1849",
        "numPages": "776",
        "language": "",
        "ISBN": "",
        "shortTitle": "",
        "url": "https://www.biodiversitylibrary.org/bibliography/84947",
        "accessDate": "",
        "archive": "done",
        "archiveLocation": "",
        "libraryCatalog": "BHL",
        "callNumber": "",
        "rights": "",
        "extra": "LD: 9+",
        "tags": [],
        "collections": ["KXUA5LUF"],
        "relations": {},
        "dateAdded": "2018-03-26T14:30:11Z",
        "dateModified": "2018-03-26T14:37:26Z"
    }
}, {
    "title": "The Landscape Gardening and Landscape Architecture of the Late Humphrey Repton",
    "data": {
        "key": "G9XEILXC",
        "version": 3280,
        "itemType": "book",
        "title": "The landscape gardening and landscape architecture of the late Humphrey Repton, esq.: being his entire works on these subjects.",
        "creators": [{
            "creatorType": "author",
            "firstName": "Humphry",
            "lastName": "Repton"
        }, {
            "creatorType": "author",
            "firstName": "J. C.",
            "lastName": "Loudon"
        }],
        "abstractNote": "",
        "series": "",
        "seriesNumber": "",
        "volume": "",
        "numberOfVolumes": "",
        "edition": "",
        "place": "London, Farnborough",
        "publisher": "Printed for the editor, [etc., etc.] Gregg",
        "date": "1840 ;1969]",
        "numPages": "xxxi, 619, [1] p.",
        "language": "",
        "ISBN": "",
        "shortTitle": "The landscape gardening and landscape architecture of the late Humphrey Repton, esq.",
        "url": "https://catalog.hathitrust.org/Record/001506440",
        "accessDate": "2018-09-14T23:00:13Z",
        "archive": "",
        "archiveLocation": "",
        "libraryCatalog": "Hathi Trust",
        "callNumber": "",
        "rights": "",
        "extra": "",
        "tags": [{
            "tag": "Architecture, Domestic",
            "type": 1
        }, {
            "tag": "Landscape architecture",
            "type": 1
        }],
        "collections": ["LMWECFU5"],
        "relations": {},
        "dateAdded": "2018-09-14T23:00:13Z",
        "dateModified": "2018-09-14T23:00:13Z"
    }
}, {
    "title": "The Origin of Species",
    "data": {
        "key": "CPIDYZER",
        "version": 3283,
        "itemType": "book",
        "title": "The origin of species by means of natural selection, or, the preservation of favoured races in the struggle for life",
        "creators": [{
            "creatorType": "author",
            "firstName": "Charles",
            "lastName": "Darwin"
        }],
        "abstractNote": "",
        "series": "",
        "seriesNumber": "",
        "volume": "",
        "numberOfVolumes": "",
        "edition": "Sixth edition / with additions and corrections. (Eleventh thousand.)",
        "place": "London :",
        "publisher": "John Murray,",
        "date": "",
        "numPages": "492",
        "language": "",
        "ISBN": "",
        "shortTitle": "",
        "url": "https://www.biodiversitylibrary.org/item/124544",
        "accessDate": "",
        "archive": "",
        "archiveLocation": "",
        "libraryCatalog": "",
        "callNumber": "",
        "rights": "",
        "extra": "",
        "tags": [],
        "collections": ["KXUA5LUF"],
        "relations": {},
        "dateAdded": "2018-09-14T23:01:00Z",
        "dateModified": "2018-09-14T23:01:00Z"
    }
}, {
    "title": "The Papers of Frederick Law Olmsted",
    "data": {
        "key": "MZXSPD66",
        "version": 3234,
        "itemType": "book",
        "title": "The Papers of Frederick Law Olmsted: Supplementary Series",
        "creators": [{
            "creatorType": "author",
            "firstName": "Frederick Law",
            "lastName": "Olmsted"
        }],
        "abstractNote": "",
        "series": "",
        "seriesNumber": "",
        "volume": "",
        "numberOfVolumes": "",
        "edition": "",
        "place": "Baltimore :",
        "publisher": "Johns Hopkins University Press,",
        "date": "c1997-",
        "numPages": "",
        "language": "",
        "ISBN": "978-0-8018-5532-0",
        "shortTitle": "",
        "url": "",
        "accessDate": "",
        "archive": "",
        "archiveLocation": "",
        "libraryCatalog": "",
        "callNumber": "",
        "rights": "",
        "extra": "",
        "tags": [],
        "collections": ["AYFZDCDI"],
        "relations": {},
        "dateAdded": "2018-09-14T22:13:09Z",
        "dateModified": "2018-09-14T22:13:48Z"
    }
}, {
    "title": "The Wild Garden",
    "data": {
        "key": "YW5VIQJE",
        "version": 674,
        "itemType": "book",
        "title": "The wild garden, or the naturalization and natural grouping of hardy exotic plants with a chapter on the garden of British wild flowers.",
        "creators": [{
            "creatorType": "author",
            "firstName": "W.",
            "lastName": "Robinson"
        }],
        "abstractNote": "",
        "series": "",
        "seriesNumber": "",
        "volume": "",
        "numberOfVolumes": "",
        "edition": "4th ed. Illustrated by Alfred Parson.",
        "place": "London,",
        "publisher": "J. Murray,",
        "date": "1894",
        "numPages": "336",
        "language": "",
        "ISBN": "",
        "shortTitle": "",
        "url": "https://www.biodiversitylibrary.org/bibliography/54756",
        "accessDate": "",
        "archive": "",
        "archiveLocation": "",
        "libraryCatalog": "",
        "callNumber": "",
        "rights": "",
        "extra": "",
        "tags": [],
        "collections": ["KXUA5LUF"],
        "relations": {},
        "dateAdded": "2018-03-26T15:55:45Z",
        "dateModified": "2018-03-26T15:55:45Z"
    }
}, {
    "title": "To Live in the New World",
    "data": {
        "key": "8N2HR2TD",
        "version": 3228,
        "itemType": "book",
        "title": "To live in the New World : A.J. Downing and American landscape gardening /",
        "creators": [{
            "creatorType": "author",
            "firstName": "Judith K.",
            "lastName": "Major"
        }],
        "abstractNote": "",
        "series": "",
        "seriesNumber": "",
        "volume": "",
        "numberOfVolumes": "",
        "edition": "",
        "place": "Cambridge, Mass. :",
        "publisher": "MIT Press,",
        "date": "c1997.",
        "numPages": "",
        "language": "",
        "ISBN": "978-0-262-13331-9",
        "shortTitle": "To live in the New World",
        "url": "",
        "accessDate": "",
        "archive": "",
        "archiveLocation": "",
        "libraryCatalog": "",
        "callNumber": "",
        "rights": "",
        "extra": "",
        "tags": [],
        "collections": ["AYFZDCDI"],
        "relations": {},
        "dateAdded": "2018-09-14T21:56:23Z",
        "dateModified": "2018-09-14T21:56:23Z"
    }
}, {
    "title": "Treatise on the Theory and Practice of Landscape Gardening, Adapted to North America",
    "data": {
        "key": "EI2VS2WB",
        "version": 413,
        "itemType": "book",
        "title": "A treatise on the theory and practice of landscape gardening, adapted to North America ...",
        "creators": [{
            "creatorType": "author",
            "firstName": "A. J.",
            "lastName": "Downing"
        }, {
            "creatorType": "author",
            "firstName": "Henry Winthrop",
            "lastName": "Sargent"
        }],
        "abstractNote": "",
        "series": "",
        "seriesNumber": "",
        "volume": "",
        "numberOfVolumes": "",
        "edition": "",
        "place": "New York",
        "publisher": "A. O. Moore & Co.",
        "date": "1859",
        "numPages": "xvi, 576 p.",
        "language": "",
        "ISBN": "",
        "shortTitle": "",
        "url": "https://catalog.hathitrust.org/Record/011602086",
        "accessDate": "2018-03-23T23:16:54Z",
        "archive": "done",
        "archiveLocation": "",
        "libraryCatalog": "Hathi Trust",
        "callNumber": "",
        "rights": "",
        "extra": "LD: 9",
        "tags": [{
            "tag": "Landscape gardening",
            "type": 1
        }],
        "collections": ["LMWECFU5"],
        "relations": {},
        "dateAdded": "2018-03-23T23:16:54Z",
        "dateModified": "2018-03-24T13:21:11Z"
    }
}, {
    "title": "Walks and Talks of an American Farmer in England",
    "data": {
        "key": "B2ELT9P4",
        "version": 790,
        "itemType": "book",
        "title": "Walks and talks of an American farmer in England.",
        "creators": [{
            "creatorType": "author",
            "firstName": "Frederick Law",
            "lastName": "Olmsted"
        }],
        "abstractNote": "",
        "series": "Central Park",
        "seriesNumber": "",
        "volume": "",
        "numberOfVolumes": "",
        "edition": "",
        "place": "New York",
        "publisher": "G.P. Putnam and company",
        "date": "1852",
        "numPages": "2 v. in 1",
        "language": "",
        "ISBN": "",
        "shortTitle": "",
        "url": "https://catalog.hathitrust.org/Record/008727397",
        "accessDate": "2018-03-26T15:11:29Z",
        "archive": "done",
        "archiveLocation": "",
        "libraryCatalog": "Hathi Trust",
        "callNumber": "",
        "rights": "",
        "extra": "LD: 9+",
        "tags": [{
            "tag": "Agriculture",
            "type": 1
        }, {
            "tag": "Description and travel.",
            "type": 1
        }, {
            "tag": "England",
            "type": 1
        }, {
            "tag": "England.",
            "type": 1
        }],
        "collections": ["LMWECFU5"],
        "relations": {},
        "dateAdded": "2018-03-26T15:11:29Z",
        "dateModified": "2018-03-26T17:31:49Z"
    }
}];
module.exports = resources
